apiVersion: v1
kind: Service
metadata:
  name: myapp-pod-loadbalancer-service

spec:
  type: LoadBalancer
  selector: 
    app: myapp
  ports:
    - name: http
      port: 80
      targetPort: 80
# Types of Kubernetes Objects
# Pod, ReplicaSet, Deployment, Service and many more

# apiVersion: version of k8s objects
# kind: k8s objects 
# metadata: define name and labels for k8s objects
# spec: specification or real definition for k8s objects
